# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ana_sayfa.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1119, 758)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-20, -20, 1181, 801))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("pngtree-3d-creative-online-shopping-elements-backgrouns-picture-image_2151188.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(290, 30, 591, 41))
        self.label_2.setObjectName("label_2")
        self.profil = QtWidgets.QPushButton(Form)
        self.profil.setGeometry(QtCore.QRect(60, 150, 201, 181))
        self.profil.setObjectName("profil")
        self.stokdurum = QtWidgets.QPushButton(Form)
        self.stokdurum.setGeometry(QtCore.QRect(470, 150, 201, 181))
        self.stokdurum.setObjectName("stokdurum")
        self.calisanlar = QtWidgets.QPushButton(Form)
        self.calisanlar.setGeometry(QtCore.QRect(850, 150, 201, 181))
        self.calisanlar.setObjectName("calisanlar")
        self.satis = QtWidgets.QPushButton(Form)
        self.satis.setGeometry(QtCore.QRect(50, 520, 201, 181))
        self.satis.setObjectName("satis")
        self.iade = QtWidgets.QPushButton(Form)
        self.iade.setGeometry(QtCore.QRect(460, 520, 201, 181))
        self.iade.setObjectName("iade")
        self.cikisyap = QtWidgets.QPushButton(Form)
        self.cikisyap.setGeometry(QtCore.QRect(850, 520, 201, 181))
        self.cikisyap.setObjectName("cikisyap")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#f30000;\">ANA SAYFA</span></p></body></html>"))
        self.profil.setText(_translate("Form", "Profil"))
        self.stokdurum.setText(_translate("Form", "Stok Durum"))
        self.calisanlar.setText(_translate("Form", "Çalışanlar"))
        self.satis.setText(_translate("Form", "Satış"))
        self.iade.setText(_translate("Form", "İade"))
        self.cikisyap.setText(_translate("Form", "Çıkış Yap"))
