# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calisanlar_.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(978, 750)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-20, -40, 1081, 791))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Adsız.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(180, 30, 591, 51))
        self.label_2.setObjectName("label_2")
        self.calisanlar = QtWidgets.QTableWidget(Form)
        self.calisanlar.setGeometry(QtCore.QRect(150, 110, 661, 531))
        self.calisanlar.setObjectName("calisanlar")
        self.calisanlar.setColumnCount(0)
        self.calisanlar.setRowCount(0)
        self.getir = QtWidgets.QPushButton(Form)
        self.getir.setGeometry(QtCore.QRect(740, 672, 75, 31))
        self.getir.setObjectName("getir")
        self.calisanadedi = QtWidgets.QLineEdit(Form)
        self.calisanadedi.setGeometry(QtCore.QRect(350, 680, 131, 21))
        self.calisanadedi.setObjectName("calisanadedi")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(150, 660, 181, 51))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#f30000;\">ÇALIŞANLAR</span></p></body></html>"))
        self.getir.setText(_translate("Form", "Getir"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#f30000;\">Çalışan Adedi :</span></p></body></html>"))
