# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'giris_yap.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(927, 566)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-20, -20, 981, 791))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Adsız.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(180, 60, 591, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(250, 250, 171, 51))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(340, 350, 71, 41))
        self.label_4.setObjectName("label_4")
        self.girisyap = QtWidgets.QPushButton(Form)
        self.girisyap.setGeometry(QtCore.QRect(450, 430, 101, 31))
        self.girisyap.setObjectName("girisyap")
        self.sifreyigoster = QtWidgets.QCheckBox(Form)
        self.sifreyigoster.setGeometry(QtCore.QRect(580, 400, 101, 17))
        self.sifreyigoster.setObjectName("sifreyigoster")
        self.kulladi = QtWidgets.QLineEdit(Form)
        self.kulladi.setGeometry(QtCore.QRect(440, 270, 131, 21))
        self.kulladi.setObjectName("kulladi")
        self.sifre = QtWidgets.QLineEdit(Form)
        self.sifre.setGeometry(QtCore.QRect(440, 360, 131, 21))
        self.sifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.sifre.setObjectName("sifre")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#f30000;\">MAĞAZA TAKİP UYGULAMASI</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#f30000;\">Kullanıcı Adı :</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#f30000;\">Şifre :</span></p></body></html>"))
        self.girisyap.setText(_translate("Form", "Giriş Yap"))
        self.sifreyigoster.setText(_translate("Form", "Şifreyi Göster"))
