# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profil_.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(908, 683)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-10, -10, 941, 711))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Adsız.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(160, 30, 591, 41))
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(330, 540, 141, 31))
        self.label_6.setObjectName("label_6")
        self.dogrula = QtWidgets.QPushButton(Form)
        self.dogrula.setGeometry(QtCore.QRect(460, 460, 101, 31))
        self.dogrula.setObjectName("dogrula")
        self.yenisifre = QtWidgets.QLineEdit(Form)
        self.yenisifre.setGeometry(QtCore.QRect(490, 550, 113, 20))
        self.yenisifre.setObjectName("yenisifre")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(560, 160, 71, 31))
        self.label_3.setObjectName("label_3")
        self.unvan = QtWidgets.QLineEdit(Form)
        self.unvan.setGeometry(QtCore.QRect(642, 340, 111, 20))
        self.unvan.setObjectName("unvan")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(300, 600, 181, 31))
        self.label_7.setObjectName("label_7")
        self.goruntu = QtWidgets.QGraphicsView(Form)
        self.goruntu.setGeometry(QtCore.QRect(20, 110, 471, 341))
        self.goruntu.setObjectName("goruntu")
        self.sifremidegistir = QtWidgets.QPushButton(Form)
        self.sifremidegistir.setGeometry(QtCore.QRect(630, 610, 101, 31))
        self.sifremidegistir.setObjectName("sifremidegistir")
        self.sifretekrar = QtWidgets.QLineEdit(Form)
        self.sifretekrar.setGeometry(QtCore.QRect(490, 610, 113, 20))
        self.sifretekrar.setObjectName("sifretekrar")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(530, 240, 101, 41))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(530, 320, 91, 51))
        self.label_5.setObjectName("label_5")
        self.soyad = QtWidgets.QLineEdit(Form)
        self.soyad.setGeometry(QtCore.QRect(640, 250, 111, 20))
        self.soyad.setObjectName("soyad")
        self.ad = QtWidgets.QLineEdit(Form)
        self.ad.setGeometry(QtCore.QRect(640, 170, 111, 20))
        self.ad.setObjectName("ad")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#f30000;\">PROFİL</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#ff0000;\">Yeni Şifre :</span></p></body></html>"))
        self.dogrula.setText(_translate("Form", "Doğrula"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#ff0000;\">Ad :</span></p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#ff0000;\">Şifre Tekrar :</span></p></body></html>"))
        self.sifremidegistir.setText(_translate("Form", "Şifremi Değiştir"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#ff0000;\">Soyad :</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#ff0000;\">Unvan :</span></p></body></html>"))
