# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stok_durum.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(978, 719)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-10, -30, 1051, 761))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Adsız.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(190, 40, 591, 41))
        self.label_2.setObjectName("label_2")
        self.urunler = QtWidgets.QTableWidget(Form)
        self.urunler.setGeometry(QtCore.QRect(170, 110, 661, 411))
        self.urunler.setObjectName("urunler")
        self.urunler.setColumnCount(0)
        self.urunler.setRowCount(0)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(530, 560, 171, 41))
        self.label_3.setObjectName("label_3")
        self.urunadedi = QtWidgets.QLineEdit(Form)
        self.urunadedi.setGeometry(QtCore.QRect(720, 570, 113, 20))
        self.urunadedi.setObjectName("urunadedi")
        self.kategoriler = QtWidgets.QComboBox(Form)
        self.kategoriler.setGeometry(QtCore.QRect(370, 570, 111, 22))
        self.kategoriler.setObjectName("kategoriler")
        self.kategoriler.addItem("")
        self.kategoriler.setItemText(0, "")
        self.kategoriler.addItem("")
        self.kategoriler.addItem("")
        self.kategoriler.addItem("")
        self.kategoriler.addItem("")
        self.kategoriler.addItem("")
        self.kategoriler.addItem("")
        self.kategoriler.addItem("")
        self.kategoriler.addItem("")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(160, 560, 191, 41))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#f30000;\">STOK DURUM</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#f30000;\">Ürün Adedi :</span></p></body></html>"))
        self.kategoriler.setItemText(1, _translate("Form", "Ev Eşyaları"))
        self.kategoriler.setItemText(2, _translate("Form", "Elektronik"))
        self.kategoriler.setItemText(3, _translate("Form", "Kişisel Bakım"))
        self.kategoriler.setItemText(4, _translate("Form", "Yiyecek"))
        self.kategoriler.setItemText(5, _translate("Form", "Mobilya"))
        self.kategoriler.setItemText(6, _translate("Form", "Spor"))
        self.kategoriler.setItemText(7, _translate("Form", "Giyim"))
        self.kategoriler.setItemText(8, _translate("Form", "Pet"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#f30000;\">Kategori Seçin :</span></p></body></html>"))
