# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'urun_satis.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1108, 748)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-10, -10, 1141, 791))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Adsız.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.goruntu = QtWidgets.QGraphicsView(Form)
        self.goruntu.setGeometry(QtCore.QRect(250, 100, 571, 461))
        self.goruntu.setObjectName("goruntu")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(240, 580, 131, 67))
        self.label_2.setObjectName("label_2")
        self.urunutani = QtWidgets.QPushButton(Form)
        self.urunutani.setGeometry(QtCore.QRect(740, 580, 81, 23))
        self.urunutani.setObjectName("urunutani")
        self.sat = QtWidgets.QPushButton(Form)
        self.sat.setGeometry(QtCore.QRect(530, 700, 75, 23))
        self.sat.setObjectName("sat")
        self.urunadi = QtWidgets.QLineEdit(Form)
        self.urunadi.setGeometry(QtCore.QRect(380, 600, 151, 31))
        self.urunadi.setObjectName("urunadi")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(240, 20, 591, 51))
        self.label_3.setObjectName("label_3")
        self.urunadedi = QtWidgets.QLineEdit(Form)
        self.urunadedi.setGeometry(QtCore.QRect(380, 660, 151, 31))
        self.urunadedi.setObjectName("urunadedi")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(270, 640, 101, 67))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#ff0000;\">Ürün Adı :</span></p></body></html>"))
        self.urunutani.setText(_translate("Form", "Ürünü Tanı"))
        self.sat.setText(_translate("Form", "Sat"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#f30000;\"> ÜRÜN SATIŞ PANELİ</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#ff0000;\">Adedi :</span></p></body></html>"))
